#pragma once

#include "CoreMinimal.h"

class UStaticMeshComponent;
class UTexture2D;

/**
 * Loads PNGs generated by Scripts/generate_fal_environment.py
 * from Content/FalGenerated. Safe no-op if the files are missing.
 */
struct FVIFalMedia
{
	static FString GeneratedDir();
	static UTexture2D* LoadPng(const TCHAR* Stem);
	static void ApplyIfPresent(UStaticMeshComponent* Comp, const TCHAR* Stem);
};
